#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &

# fix some Java applications
# wmname LG3D

# workspaces
bspc monitor primary -d 1 2 3 4 5 6 7
bspc monitor LVDS-1 -d 7  # TODO: multiple monitors

bspc config focus_follows_pointer true
70x100
# Window borders (Auto-Generate)
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 5
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc rule -a Pavucontrol state=floating 
bspc config gapless_monocle false
bspc config window_gap 17

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# rules
bspc rule -a feh state=floating
bspc rule -a pavucontrol state=floating rectangle=700x300+1150+50
bspc rule -a gnome-system-monitor state=floating
# bspc rule -a firefox state=tiled
# bspc rule -a firefox desktop='^2' follow=on

# start resources
xrdb merge ~/.Xresources

# python script to always initialize with a different wallpaper:
# TODO: Add loading of basic scripts
~/.config/scripts/random_wallpaper &
~/.config/polybar/launch.sh

# launch notification daemon
dunst -config ~/.config/bspwm/dunstrc &

# launch battery tracker and redshift
pkill battery-alert; /bin/battery-alert &
pgrep -x redshift > /dev/null || redshift &

# start compositor
picom --config ~/.config/bspwm/picom_configurations/1.conf &

# autostart
# flameshot &
/home/ebArch/nekoray-4.0.1-2024-12-12-linux-x64.AppImage
