#!/bin/bash

# Script to Manage Speaker Volume with ALSA (amixer) and PulseAudio (pamixer)

# Function to get volume level (using amixer for ALSA)
get_volume() {
  if command -v amixer &> /dev/null; then
    volume=$(amixer get Master | grep '\[[0-9]+%\]' | awk -F'[][]' '{print $2}' | tr -d '%')
    echo "$volume"
  else
    echo "ALSA (amixer) not found."
    exit 1
  fi
}


# Function to increase volume (using amixer)
up_volume() {
  if command -v amixer &> /dev/null; then
    amixer set Master 2%+ unmute
    dunstify -u low --replace=69 -i audio-volume-high "Volume: $(get_volume)%"
  else
    echo "ALSA (amixer) not found."
    exit 1
  fi
}

# Function to decrease volume (using amixer)
down_volume() {
  if command -v amixer &> /dev/null; then
    amixer set Master 2%- unmute
    dunstify -u low --replace=69 -i audio-volume-high "Volume: $(get_volume)%"
  else
    echo "ALSA (amixer) not found."
    exit 1
  fi
}

# Function to toggle mute (using amixer)
toggle_mute() {
  if command -v amixer &> /dev/null; then
    amixer set Master toggle
    status=$(amixer get Master | grep "\[off\]" | awk '{print $NF}' | head -1)
    if [[ "$status" == "[off]\n[off]" ]]; then
      dunstify -u low --replace=69 -i audio-volume-muted "Mute"
    else
      dunstify -u low --replace=69 -i audio-volume-high "Unmute"
    fi
  else
    echo "ALSA (amixer) not found."
    exit 1
  fi
}

# Execute actions based on arguments
if [[ "$1" == "--get" ]]; then
  get_volume
elif [[ "$1" == "--up" ]]; then
  up_volume
elif [[ "$1" == "--down" ]]; then
  down_volume
elif [[ "$1" == "--toggle" ]]; then
  toggle_mute
else
  get_volume
fi

